### ISSUE TITLE
Define content and structure of Usage Entity

### ISSUE THREAD

**Issue by cliftonc** [stichtingsem/technology-prototype#16]
Discuss and define Usage entity:

- Is it different for Marketplace vs LMS?

**Comment by mcginkel** [comment]
Ok, so Lets start on this on: Usage.

* needed to complete the money goods flow (4.4)
* usage is valid if this is based on a entitlement (or should we have usage anyway?, but how do you know ho to send usage to?)
* usage is an notification after the student starts to use the LA.
* purpose is 2 fold: Start billing process (first use), Monitor that the product is used over time (repeated use)
* it is up to the involved parties if the payment starts by first use, or when the repeated usage starts billing. 
  This might be usefull to filter out setup errors and mistries (first use) from real usage (pattern of subsequent usage)

**Based on entitlement?**
1. So we could based the usage on the entitlement:
  the LA will send notifications to MP: At 23-jan-2020 12:01, student id-xxx, accessed product :EAN, based on entitlement E-xxx
2. We just send the usage if entitlement is not available... (not prefered)

**How often**
1. send first time only
This is not prefered as you cannot see errors in setup process that make students acces a product, findout it is the wrong one, etc
2. Send everytime
3. Send ones a week ( and include number of times?)

**Comment by mcginkel** [comment]
drawing: https://yuml.me/sem/edit/fba64821

**Comment by hhaarsma** [comment]
Should we have an indication how often information should be communicated? I can imagine that notifying the market place everytime a student opens the learning application can be considered undersirable privacy sensitive information.

**Comment by hhaarsma** [comment]
Do we need to communicate the id along with the eckid?

**Comment by edwinverwoerd** [comment]
Domain of Usage is to get information about the state of an entitlement. Als MP I whant to see if the entitlement is:
1) still not used (nog niet geactiveerd)
2) used (geactiveerd)
3) blocked (geblokkeerd)
4) expirered (verlopen)

And timestamp information about. entitlement for User X has status used and the first and last time was [time stamp]

I looked at the pull request but I can not see if this will coverd the wish of a MP?
