### ISSUE TITLE
Define exchange of School Data from SIS to Marketplace

### ISSUE THREAD

**Issue by cliftonc** [stichtingsem/technology-prototype#25]

**Comment by edwinverwoerd** [comment]
On this moment we use the UWLR-FDE set to exchange this data. https://www.edustandaard.nl/standaard_afspraken/fijndistributie/fde-set1-0/ 

Current practical experience shows that the standard and technique can be used well. Problems that arise have to do with the correct use of the SIS in relation to this data set. And the lack of a technical key in case of an LMS SAAS implementation, which means that there is no clear indication of the data source. Using the BRINcode and RIO schoolid is not unique enough.

**Comment by cliftonc** [comment]
Closed in favour of #28
