### ISSUE TITLE
Define exchange of School Data from SIS to LMS

### ISSUE THREAD

**Issue by cliftonc** [stichtingsem/technology-prototype#26]

**Comment by edwinverwoerd** [comment]
This issue has a relationship with #25  and will have to be validate in terms of content against the data set that is now being exchanged via UWLR-FDE. And specifically the relationship between Pupil; Level; Grade; Class / Group and subjects. With regard to Class / Group and Subjects, we have to connect with the ITL / ELT and OBK lists

**Comment by cliftonc** [comment]
This has been captured as an initial version: This is now covered in the initial SIS definition: https://stichtingsem.stoplight.io/docs/sem-technology-prototype/reference/sisdata.v1.yaml
