### ISSUE TITLE
Define exchange of School Data from SIS to Learning Application

### ISSUE THREAD

**Issue by cliftonc** [stichtingsem/technology-prototype#27]

**Comment by edwinverwoerd** [comment]
Data from SIS to LA 

See also Issue #28 . But I think we have to check the Edustandaard UWLR-L Smalle Set also to see if we are compleet.

**Comment by cliftonc** [comment]
This exchange will be covered by the PR: #34

**Comment by cliftonc** [comment]
Closing in favour of merged PR.
