### ISSUE TITLE
Move possible implementations in their own folders.

### ISSUE THREAD

**Issue by mcginkel** [stichtingsem/technology-prototype#56]
An hour ago a possible implementation is pushed in the implementations folder as if we would only have one implementation. Can we add another level? add "possible implementation from infinitas for catalog" as sublayer.

In the instructions there is also an instruction "Get credentials to the infinitas registry which contains the avatar library (for now we have no place where to store secrets, so ask a team-mate who's working on sem):" Can we make that more generic?

**Comment by cliftonc** [comment]
Agreed - we'll move it.

**Comment by cliftonc** [comment]
https://github.com/stichtingsem/technology-prototype/tree/master/implementation/LA
